#!/usr/bin/env python3

"""Vagrant Supervisor.

Usage:
  vagrant_supervisor status [<machine>]
  vagrant_supervisor destroy <machine> <box>
  vagrant_supervisor up <machine> <box>
  vagrant_supervisor suspend <machine> <box>
  vagrant_supervisor halt <machine> <box>
  vagrant_supervisor machine add
  vagrant_supervisor machine remove <machine>

Options:
  -h --help          Show this screen
  --version          Show version.
"""

from docopt import docopt

from supervisor.config import Config
from supervisor.command import parse_cmd_args


def main():
    args = docopt(__doc__, version='Vagrant Supervisor 0.0.1')
    cmd = parse_cmd_args(args)
    user_config = Config()
    cmd.run_cmd(user_config)
    user_config.write_config()


if __name__ == '__main__':
    main()
