#!/usr/bin/env python3

"""Vagrant Supervisor.

Usage:
  vagrant_supervisor status [machine]
  vagrant_supervisor machine new
  vagrant_supervisor machine delete <machine>

Options:
  -h --help          Show this screen
  --version          Show version.
"""

import sys
import subprocess

from docopt import docopt

from manager.config import Config
from manager.parsers import parse_status

from pprint import pprint


def main():
    args = docopt(__doc__, version='Vagrant Supervisor 0.0.1')
    pprint(args)
    user_config = Config()

    command = sys.argv[1]

    if command == 'status':
        for machine in user_config.config:
            if machine['connection_type'] == 'local':
                output = subprocess.check_output(['vagrant', 'global-status',
                                                  '--prune'])
                output = str(output).split('\\n')
                status = parse_status(output)
                print(status)


if __name__ == '__main__':
    main()
